version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - cd frontend
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist

 