version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - zip -r function.zip handler.js utils/ node_modules/
      - aws s3 cp function.zip s3://my-lambda-deployments-mariam/function.zip
artifacts:
  files:
    - backend/function.zip
